### ISSUE TITLE
Changing a project from LESS to SCSS creates an error

### ISSUE THREAD

**Issue by louh** [adunkman/connect-assets#314]
I have a project that was in LESS, and I decided to try converting it to SCSS (it's easier to migrate from SCSS to PostCSS, which is where I want it to be eventually, but one step at a time). The app worked fine when connect-assets was processing a folder of LESS files. But after converting each file to SCSS and renaming the extension, and installing the `node-sass` gem, I now get this error output:

```
TypeError: /Users/lou/Repositories/codeforamerica/streetmix/app/views/_layout.jade:25
   23|     link(href='/favicon.ico', rel='shortcut icon')
   24| 
 > 25|     != css('styles')
   26| 
   27|     script.
   28|       var SITE_URL = 'http://#{ config.app_host_port }/'

[SassEngine] undefined is not a function  (in /Users/lou/Repositories/codeforamerica/streetmix/assets/css/styles.scss)
   at sassError (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/engines/sass_engine.js:57:9)
   at SassEngine.evaluate (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/engines/sass_engine.js:84:17)
   at /Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/context.js:450:26
   at Function.forEach (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/node_modules/lodash/dist/lodash.js:3298:15)
   at Context.evaluate (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/context.js:445:5)
   at new ProcessedAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/assets/processed.js:145:29)
   at /Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:539:12
   at circular_call_protection (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:512:12)
   at Index.Base.buildAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:538:10)
   at /Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:141:26
   at Index.module.exports.cacheAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/helpers/caching.js:52:12)
   at Index.buildAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:140:33)
   at Index.Base.findAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:348:15)
   at Index.findAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:114:22)
   at new BundledAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/assets/bundled.js:53:37)
   at Index.Base.buildAsset (/Users/lou/Repositories/codeforamerica/streetmix/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:535:12)
```

What's going on? A little help please?

Thanks!

**Comment by adunkman** [comment]
From the stack, it looks like SASS is evaluating your file and is encountering an error. 

`codeforamerica/streetmix/assets/css/styles.scss`  (`undefined is not a function`). 

You might want to double-check that your SASS is valid, that’s where I would start looking! :)

**Comment by louh** [comment]
Thanks, @adunkman. I used a script that converted LESS to SCSS, but it had introduced some errors or not caught everything. I'm closing this now as going through it with a validator helped solve my problem.
