### ISSUE TITLE
Fails to compile compressed assets when using bourbon/sass (5.0.1)

### ISSUE THREAD

**Issue by grokasm** [adunkman/connect-assets#329]
I recently updated connect-assets from 3.0.2 to 5.0.1 and all asset compilation has broken.
The error I am seeing is:
```
CssSyntaxError: [CsswringCompressor] <css input>:1:1: Unknown word  (in /home/dima/dev/copthis/copthis-website/node_modules/node-bourbon/assets/stylesheets/_bourbon.scss)
// Settings
^
@import "settings/prefixer";
    at Input.error (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/node_modules/postcss/lib/input.js:65:21)
    at Parser.word (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/node_modules/postcss/lib/parser.js:184:30)
    at Parser.loop (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/node_modules/postcss/lib/parser.js:61:26)
    at Object.parse [as default] (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/node_modules/postcss/lib/parse.js:21:12)
    at new LazyResult (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/node_modules/postcss/lib/lazy-result.js:54:42)
    at Processor.process (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/node_modules/postcss/lib/processor.js:30:16)
    at CSSWring.wring (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/lib/csswring.js:559:38)
    at Function.csswring.wring (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/csswring/lib/csswring.js:572:25)
    at CsswringCompressor.compile (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/mincer/lib/mincer/compressors/csswring_compressor.js:50:23)
    at CsswringCompressor.evaluate (/home/dima/dev/copthis/copthis-website/node_modules/connect-assets/node_modules/mincer/lib/mincer/compressors/csswring_compressor.js:64:17)
```
This only happens with compression enabled.
For some reason the postcss parser seems to be having an issue with the comments in the _bourbon.scss file.
I'm not sure if this is a connect-assets/mincer/csswring/postcss issue.

**Comment by mecab** [comment]
I hope you have already solved it, but pass the option like:
``` { precompile: ["style.css"] }```.
```style.css``` should be the filename suitable for the SCSS/SASS you made.

without the option (defaults to "*"), mincer cannot know the entry point to compile and start compilation from an improper file in ```paths``` (could be a part of bourbon).

**Comment by grokasm** [comment]
Thanks @mecab! I had worked around it by keeping the older version, I'll attempt to upgrade with precompilation when I get a chance and update the issue with the results.

**Comment by aug-riedinger** [comment]
I'm having the same issue, after upgrading also.

@mecab thanks for support, but I don't understand your comment. Files should be called `styles.scss.css`? Sounds weird, in sprocket, it is usually `styles.css.scss`.

Anyways, I understand that what was failing were the comments so I removed them also... but is it a satisfying solution?

**Comment by mecab** [comment]
@aug-riedinger It's my typo, `styles.css.scss` is correct as sprocket way. Sorry for confusing you.

I'm not sure whether removing comment from bourbon works or not, because I haven't tried to do that (I guess it works, though). However my workaround concludes within the scope of your code (e.g., you won't need to patch to bourbon and any dependencies). I put bourbon in my project via `node-bourbon` package, so I didn't want to make the change in it.

Of course, the radical issue lies on one of connect-assets, mincer, csswring or postcss. `//` style comment is valid in SCSS.

**Comment by aug-riedinger** [comment]
Thanks!

**Comment by blakevanlan** [comment]
Closing this for now. If it's still a problem please reopen.
